# Generated by Django 3.1.1 on 2020-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.CharField(max_length=6),
        ),
    ]
